version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: travel
      MYSQL_USER: traveluser
      MYSQL_PASSWORD: travelpass
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: traveluser
      DB_PASSWORD: travelpass
      DB_NAME: travel
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u traveluser -ptravelpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  ia:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      IA_HOST: ia
      IA_PORT: 11434
    restart: always
    volumes:
      - ollama_data:/root/.ollama

volumes:
  db_data:
  ollama_data: