name: CI - Go API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupération du code
      - name: Checkout
        uses: actions/checkout@v3

      # Installation de Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      # Téléchargement des dépendances
      - name: Install dependencies
        run: go mod tidy

      # Build de l’API
      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Test
        run: go test ./... -v -cover
